import std.collection.HashMap

func check_dict_case(dict: HashMap<String, String>): Bool {
    /*
    Given a dictionary, return true if all keys are strings in lower 
    case or all keys are strings in upper case, else return false.
    The function should return false is the given dictionary is empty.
    Examples:
    check_dict_case(HashMap<String, String>([("a","apple"), ("b","banana")])) should return true.
    check_dict_case(HashMap<String, String>([("a","apple"), ("A","banana"), ("B","banana")])) should return false.
    check_dict_case(HashMap<String, String>([("a","apple"), ("8","banana"), ("a","apple")])) should return false.
    check_dict_case(HashMap<String, String>([("Name","John"), ("Age","36"), ("City","Houston")])) should return false.
    check_dict_case(HashMap<String, String>([("STATE","NC"), ("ZIP","12345")])) should return true.
    */
    
}
