import std.collection.ArrayList

func sort_even(l: ArrayList<Int64>): ArrayList<Int64> {
    /*
    This function takes a list l and returns a list l' such that
    l' is identical to l in the odd indicies, while its values at the even indicies are equal
    to the values of the even indicies of l, but sorted.
    >>> sort_even(ArrayList<Int64>([1, 2, 3]))
    [1, 2, 3]
    >>> sort_even(ArrayList<Int64>([5, 6, 3, 4]))
    [3, 6, 5, 4]
    */
    
}
