import std.collection.ArrayList

func find_max(words: ArrayList<String>): String {
    /*
    Write a function that accepts a list of strings.
    The list contains different words. Return the word with maximum number
    of unique characters. If multiple strings have maximum number of unique
    characters, return the one which comes first in lexicographical order.

    find_max(ArrayList<String>(["name", "of", "string"])) == "string"
    find_max(ArrayList<String>(["name", "enam", "game"])) == "enam"
    find_max(ArrayList<String>(["aaaaaaa", "bb" ,"cc"])) == "aaaaaaa"
    */
    
}
