import std.collection.ArrayList

func double_the_difference(lst: ArrayList<Float64>): Int64 {
    /*
    Given a list of numbers, return the sum of squares of the numbers
    in the list that are odd. Ignore numbers that are negative or not integers.
    
    double_the_difference(ArrayList<Float64>([1.0, 3.0, 2.0, 0.0])) == 1 + 9 + 0 + 0 = 10
    double_the_difference(ArrayList<Float64>([-1.0, -2.0, 0.0])) == 0
    double_the_difference(ArrayList<Float64>([9.0, -2.0])) == 81
    double_the_difference(ArrayList<Float64>([0.0])) == 0  
   
    If the input list is empty, return 0.
    */
    
}
