import std.collection.ArrayList
import std.math.abs

func find_closest_elements(numbers: ArrayList<Float64>): (Float64, Float64) {
    /*
    From a supplied list of numbers (of length at least two) select and return two that are the closest to each
    other and return them in order (smaller number, larger number).
    >>> find_closest_elements(ArrayList<Float64>([1.0, 2.0, 3.0, 4.0, 5.0, 2.2]))
    (2.0, 2.2)
    >>> find_closest_elements(ArrayList<Float64>([1.0, 2.0, 3.0, 4.0, 5.0, 2.0]))
    (2.0, 2.0)
    */
    
}
