import std.collection.ArrayList

func order_by_points(nums: ArrayList<Int64>): ArrayList<Int64> {
    /*
    Write a function which sorts the given list of integers
    in ascending order according to the sum of their digits.
    Note: if there are several items with similar sum of their digits,
    order them based on their index in original list.

    For example:
    >>> order_by_points(ArrayList<Int64>([1, 11, -1, -11, -12])) == [-1, -11, 1, -12, 11]
    >>> order_by_points(ArrayList<Int64>([])) == []
    */
    
}
