
func same_chars(s0: String, s1: String): Bool {
    /*
    Check if two words have the same characters.
    >>> same_chars('eabcdzzzz', 'dddzzzzzzzddeddabc')
    true
    >>> same_chars('abcd', 'dddddddabc')
    true
    >>> same_chars('dddddddabc', 'abcd')
    true
    >>> same_chars('eabcd', 'dddddddabc')
    false
    >>> same_chars('abcd', 'dddddddabce')
    false
    >>> same_chars('eabcdzzzz', 'dddzzzzzzzddddabc')
    false
    */
    
}
