func test_datetime_to_string_1() {
    let timeutils = TimeUtils()
    if (timeutils.datetime_to_string(timeutils.datetime) != timeutils.datetime.format("yyyy-MM-dd HH:mm:ss")) {
        throw Exception("Test failed!")
    }
}

func test_datetime_to_string_2() {
    let timeutils = TimeUtils()
    if (timeutils.datetime_to_string(timeutils.datetime) != timeutils.datetime.format("yyyy-MM-dd HH:mm:ss")) {
        throw Exception("Test failed!")
    }
}

func test_datetime_to_string_3() {
    let timeutils = TimeUtils()
    if (timeutils.datetime_to_string(timeutils.datetime) != timeutils.datetime.format("yyyy-MM-dd HH:mm:ss")) {
        throw Exception("Test failed!")
    }
}

func test_datetime_to_string_4() {
    let timeutils = TimeUtils()
    if (timeutils.datetime_to_string(timeutils.datetime) != timeutils.datetime.format("yyyy-MM-dd HH:mm:ss")) {
        throw Exception("Test failed!")
    }
}

func test_datetime_to_string_5() {
    let timeutils = TimeUtils()
    if (timeutils.datetime_to_string(timeutils.datetime) != timeutils.datetime.format("yyyy-MM-dd HH:mm:ss")) {
        throw Exception("Test failed!")
    }
}

main() {
    test_datetime_to_string_1()
    test_datetime_to_string_2()
    test_datetime_to_string_3()
    test_datetime_to_string_4()
    test_datetime_to_string_5()
}