import std.convert.Parsable

class BigNumCalculator {

    /*
    This is a class that implements big number calculations, including adding, subtracting and multiplying.
    */

    public static func add(num1: String, num2: String): String {
        /*
        Adds two big numbers.
        :param num1: The first number to add,String.
        :param num2: The second number to add,String.
        :return: The sum of the two numbers,String.
        >>> BigNumCalculator.add("12345678901234567890", "98765432109876543210")
        '111111111011111111100'

        */

    }

    public static func subtract(num1: String, num2: String): String {
        /*
        Subtracts two big numbers.
        :param num1: The first number to subtract,String.
        :param num2: The second number to subtract,String.
        :return: The difference of the two numbers,String.
        >>> BigNumCalculator.subtract("12345678901234567890", "98765432109876543210")
        '-86419753208641975320'

        */

    }

    public static func multiply(num1: String, num2: String): String {
        /*
        Multiplies two big numbers.
        :param num1: The first number to multiply,String.
        :param num2: The second number to multiply,String.
        :return: The product of the two numbers,String.
        >>> BigNumCalculator.multiply("12345678901234567890", "98765432109876543210")
        '1219326311370217952237463801111263526900'

        */
        
    }
}
